name: Events Demo 1
on: 
  pull_request:
    types:
      - opened
    branches:
      - master # matches only master branch
      - dev-* # matches dev-anything-here
      - feat/** # matches feat/anything/here
  workflow_dispatch:
  push:
    branches:
      - master
      - 'dev-*'
      - 'feat/**'
    paths-ignore:
      - '.github/workflows/*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Output Event Name
        run: echo "Event name is ${{ github.event }}"
      - name: Get code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Test code
        run: npm run test
      - name: Build code
        run: npm run build
      - name: Deploy project
        run: echo "Deploying project..."